# Use Python base image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Expose port wherexs app will run
EXPOSE 8888

# Set entry point command
CMD ["python", "api.py"]